### ISSUE TITLE
CLI too bright background text color

### ISSUE THREAD

**Issue by pandasoli** [extension-js/extension.js#240]
![image](https://github.com/user-attachments/assets/dcaeb8a7-fd04-4d78-8489-ab871bad1572)

I was taking a look at the project's code and the lib used to print colors but I couldn't find the reason (issue showed in the picture above) so I'm making this issue.
PS: The text is not being selected by the terminal's cursor.

**Environment**  
Terminal: Alacritty

<details>
  <summary>Theme:</summary>

```toml
# (Github Dark High Contrast) Colors for Alacritty

[colors.bright]
black = "#4c566a"
blue = "#81a1c1"
cyan = "#8fbcbb"
green = "#a3be8c"
magenta = "#b48ead"
red = "#bf616a"
white = "#eceff4"
yellow = "#ebcb8b"

[colors.cursor]
cursor = "#d8dee9"
text = "#2e3440"

[colors.dim]
black = "#373e4d"
blue = "#68809a"
cyan = "#6d96a5"
green = "#809575"
magenta = "#8c738c"
red = "#94545d"
white = "#aeb3bb"
yellow = "#b29e75"

[colors.normal]
black = "#3b4252"
blue = "#81a1c1"
cyan = "#88c0d0"
green = "#a3be8c"
magenta = "#b48ead"
red = "#bf616a"
white = "#e5e9f0"
yellow = "#ebcb8b"

[colors.primary]
background = "#0a0c10"
dim_foreground = "#a5abb6"
foreground = "#d8dee9"
```
</details>
